<a href="https://colab.research.google.com/github/Ibreez16/pandas_learning/blob/main/Pandas_Practice_(4_5).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Questions based on Titanic Dataset:**

To read the dataset as csv, use the below code:

```python
import pandas as pd

url = "https://docs.google.com/spreadsheets/d/e/2PACX-1vQjh5HzZ1N0SU7ME9ZQRzeVTaXaGsV97rU8R7eAcg53k27GTstJp9cRUOfr55go1GRRvTz1NwvyOnuh/pub?gid=1562145139&single=true&output=csv"
titanic_df = pd.read_csv(url)
```

In [ ]:
import numpy as np
import pandas as pd

url = "https://docs.google.com/spreadsheets/d/e/2PACX-1vQjh5HzZ1N0SU7ME9ZQRzeVTaXaGsV97rU8R7eAcg53k27GTstJp9cRUOfr55go1GRRvTz1NwvyOnuh/pub?gid=1562145139&single=true&output=csv"
titanic_df = pd.read_csv(url)

### `Q-1:` Using `groupby` make groups using the `"Pclass"` column and find out the average age and total number of missing values in the `"Age"` column for every group.

In [ ]:
# code here
class_group = titanic_df.groupby("Pclass")["Age"].agg(
    avg_age= 'mean',
    total_missing_values = lambda x:x.isnull().sum()
)
class_group

          avg_age  total_missing_values
Pclass
1       38.233441                    30
2       29.877630                    11
3       25.140620                   136

In [ ]:
titanic_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

### `Q-2:` Using `groupby` make groups using the `"Pclass"` column and fill every group's `"Embarked"` column's missing values with the mode value of that group. After that, print every group's `"Embarked"` column's value counts in ascending order.

In [ ]:
# code here
group_class = titanic_df.groupby("Pclass")["Embarked"].fillna("mode")
group_class.value_counts().sort_values(ascending=False)

/tmp/ipykernel_911/1581627172.py:2: FutureWarning: SeriesGroupBy.fillna is deprecated and will be removed in a future version. Use obj.ffill() or obj.bfill() for forward or backward filling instead. If you want to fill with a single value, use Series.fillna instead
  group_class = titanic_df.groupby("Pclass")["Embarked"].fillna("mode")

Embarked
S       644
C       168
Q        77
mode      2
Name: count, dtype: int64

### `Q-3:` Make groups based on `"Embarked"` column. And for each of this embarked group, make another group based on `"Pclass"` and find out the average fare (round off up to 2 decimal places) for each "Pclass" for each group of "Embarked".

**Sample Output:**

```bash
{'C': {1: 105, 2: 25, 3: 11},
 'Q': {1: 90, 2: 12, 3: 11},
 'S': {1: 70, 2: 20, 3: 15}}
```

In [ ]:
# code here
result_df = titanic_df.groupby(["Embarked","Pclass"])
result_df["Fare"].mean().round(2)

Embarked  Pclass
C         1         104.72
          2          25.36
          3          11.21
Q         1          90.00
          2          12.35
          3          11.18
S         1          70.36
          2          20.33
          3          14.64
Name: Fare, dtype: float64

## **Questions Based on Fifa Worldcup - 2022 Dataset:**

You can read the dataset by using the below sample code

```python
import pandas as pd

fifa_df = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vT3D_x_4DS6d51LKJ7ze1sxT5WpV5uiSVOFYHLwBiGru6vFyVv5h5-83AwFjxWYiWfCDjDAaarHAV-k/pub?gid=0&single=true&output=csv")
```

In [ ]:
import pandas as pd
import numpy as np

fifa_df = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vT3D_x_4DS6d51LKJ7ze1sxT5WpV5uiSVOFYHLwBiGru6vFyVv5h5-83AwFjxWYiWfCDjDAaarHAV-k/pub?gid=0&single=true&output=csv")

In [ ]:
fifa_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128 entries, 0 to 127
Data columns (total 38 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Sl. No                           128 non-null    int64
 1   Match No.                        128 non-null    int64
 2   Team                             128 non-null    object
 3   Against                          128 non-null    object
 4   Group                            128 non-null    object
 5   Goal                             128 non-null    int64
 6   Possession (%)                   128 non-null    int64
 7   Inside Penalty Area              128 non-null    int64
 8   Outside Penalty Area             128 non-null    int64
 9   Assists                          128 non-null    int64
 10  Total Attempts                   128 non-null    int64
 11  On Target                        128 non-null    int64
 12  Off Target                       128 non-null    int64
 13  Target in Penalty                128 non-null    int64
 14  Target from Outside              128 non-null    int64
 15  Left Channel                     128 non-null    int64
 16  Left Inside Channel              128 non-null    int64
 17  Central Channel                  128 non-null    int64
 18  Right Inside Channel             128 non-null    int64
 19  Right Channel                    128 non-null    int64
 20  Receptions MD                    128 non-null    int64
 21  Receptions D                     128 non-null    int64
 22  Attempted Line Breaks            128 non-null    int64
 23  Completed Line Breaks            128 non-null    int64
 24  Attempted Defensive Line Breaks  128 non-null    int64
 25  Completed Defensive Line Breaks  128 non-null    int64
 26  Yellow Cards                     128 non-null    int64
 27  Red Cards                        128 non-null    int64
 28  Fouls Against                    128 non-null    int64
 29  Offsides                         128 non-null    int64
 30  Passes                           128 non-null    int64
 31  Passes Completed                 128 non-null    int64
 32  Crosses                          128 non-null    int64
 33  Crosses Completed                128 non-null    int64
 34  Corners                          128 non-null    int64
 35  Free Kicks                       128 non-null    int64
 36  Penalties Scored                 128 non-null    int64
 37  Pts                              128 non-null    int64
dtypes: int64(35), object(3)
memory usage: 38.1+ KB

### `Q-4:` Perform `groupby` based on the `"Team"` column and then perform Z Normalization on top of the below columns of each group:
1. Passes
2. Passes Completed
3. Attempted Line Breaks
4. Completed Line Breaks

You have to make a python function named `z_normalization` which takes two arguments:

1. *group:* Every group that you have created
2. *cols_to_perform:* This parameter takes a list of columns on which you have to perform the Z-Normalization.

For this problem, you have to use th `apply()` method.

$\Large Z \ - \ Normalization = \frac{X_i - \mu}{std} $

After that find out the below values for each group:
- minimum "Passess"
- maximum "Passess"
- minimum "Yellow Cards"
- maximum "Yellow cards"
- average "Yellow Cards"
- maximum "Attempted Line Breaks"
- minimum "Attempted Line Breaks"
- standardard deviation of "Attempted Line Breaks"
- average Possession

In [ ]:
def z_normalization(group, cols_to_perform):
    #group = group.copy()
    for col in cols_to_perform:
        group[col] = (group[col] - group[col].mean()) / group[col].std()
    return group

cols = ["Passes", "Passes Completed", "Attempted Line Breaks", "Completed Line Breaks"]

normalized_group = fifa_df.groupby("Team").apply(z_normalization, cols_to_perform=cols)
normalized_group

/tmp/ipykernel_648/2498558769.py:8: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  fifa_df.groupby("Team").apply(z_normalization, cols_to_perform=cols)

               Sl. No  Match No.       Team        Against Group  Goal  \
Team
Argentina 8         9          5  Argentina   Saudi Arabia     C     1
          46       47         24  Argentina         Mexico     C     2
          77       78         39  Argentina         Poland     C     2
          98       99         50  Argentina      Australia     C     2
          115     116         58  Argentina    Netherlands     C     2
...               ...        ...        ...            ...   ...   ...
Uruguay   63       64         32    Uruguay       Portugal     H     0
          89       90         45    Uruguay          Ghana     H     2
Wales     7         8          4      Wales  United States     B     1
          32       33         17      Wales           Iran     B     0
          68       69         35      Wales        England     B     0

               Possession (%)  Inside Penalty Area  Outside Penalty Area  \
Team
Argentina 8                51                    1                     0
          46               50                    1                     1
          77               67                    1                     1
          98               53                    2                     0
          115              44                    2                     0
...                       ...                  ...                   ...
Uruguay   63               35                    0                     0
          89               39                    2                     0
Wales     7                39                    1                     0
          32               51                    0                     0
          68               33                    0                     0

               Assists  ...  Fouls Against  Offsides    Passes  \
Team                    ...
Argentina 8          0  ...              7        10 -0.208138
          46         2  ...             15         2 -0.630447
          77         2  ...             11         0  1.685214
          98         1  ...              8         4  0.622403
          115        1  ...             18         2 -0.137753
...                ...  ...            ...       ...       ...
Uruguay   63         0  ...             16         0 -0.931702
          89         1  ...             11         2 -0.124867
Wales     7          0  ...             10         1 -0.054584
          32         0  ...              9         2  1.026174
          68         0  ...             16         1 -0.971590

               Passes Completed  Crosses  Crosses Completed  Corners  \
Team
Argentina 8           -0.157888       36                 15        9
          46          -0.574048       14                  2        4
          77           1.813757       22                  5        9
          98           0.592566        6                  1        1
          115         -0.253400       16                  4        8
...                         ...      ...                ...      ...
Uruguay   63          -0.894617       18                  5        2
          89          -0.184945       15                  4        2
Wales     7           -0.139325       15                  6        3
          32           1.062357       20                  5        2
          68          -0.923031        4                  1        1

               Free Kicks  Penalties Scored  Pts
Team
Argentina 8            21                 1    0
          46           23                 0    3
          77            5                 0    3
          98           15                 0    3
          115          30                 5    3
...                   ...               ...  ...
Uruguay   63           13                 0    0
          89           20                 0    3
Wales     7            15                 1    1
          32           12                 0    1
          68           10                 0    0

[128 rows x 38 columns]

In [ ]:
cols = ["Passes", "Passes Completed", "Attempted Line Breaks", "Completed Line Breaks"]

fifa_df[cols] = fifa_df.groupby("Team")[cols].transform(lambda x: (x - x.mean()) / x.std())

In [ ]:
def get_info(group):
  dict_info = {
    'min_passes' : group["Passes"].min(),
    'max_passes' : group["Passes"].max(),
    'min_yellow' : group["Yellow Cards"].min(),
    'max_yellow' : group["Yellow Cards"].max(),
    'avg_yellow' : group["Yellow Cards"].mean(),
    'min_attempts' : group["Attempted Line Breaks"].min(),
    'max_attempts' : group["Attempted Line Breaks"].max(),
    'std_attempts' : group["Attempted Line Breaks"].std(),
    'avg_possession' : group["Possession (%)"].mean()
  }

  return pd.Series(dict_info)

In [ ]:
normalized_group.groupby("Team").agg({
    "Passes": ["min", "max"],
    "Yellow Cards": ["min", "max", "mean"],
    "Attempted Line Breaks": ["min", "max", "std"],
    "Possession (%)": "mean"
})

                  Passes           Yellow Cards                \
                     min       max          min max      mean
Team
Argentina      -1.510257  1.685214            0   8  2.285714
Australia      -1.114789  0.932782            0   3  1.750000
Belgium        -1.082696  0.888950            1   3  1.666667
Brazil         -0.928871  1.609122            0   3  1.200000
Cameroon       -0.875605  1.089713            1   5  2.666667
Canada         -1.120897  0.800641            2   4  2.666667
Costa Rica     -1.013178  0.986279            1   3  2.000000
Croatia        -1.441280  1.093005            0   2  1.142857
Denmark        -1.046208  0.946290            1   2  1.666667
Ecuador        -0.883020  1.085876            0   2  1.000000
England        -0.877731  1.705844            0   1  0.200000
France         -1.219077  1.571019            0   3  1.142857
Germany        -1.131449  0.765392            0   3  1.000000
Ghana          -1.045786  0.946861            2   4  2.666667
Iran           -0.820695  1.113800            2   3  2.333333
Japan          -1.001479  0.979825            0   3  1.500000
Korea Republic -1.157924  0.877868            1   2  1.500000
Mexico         -0.918398  1.065342            1   4  2.333333
Morocco        -1.384362  1.662218            0   3  1.285714
Netherlands    -1.051749  1.428668            0   4  1.800000
Poland         -0.694755  1.483035            1   3  1.750000
Portugal       -1.646177  1.035658            0   3  1.200000
Qatar          -1.147558  0.684833            0   4  2.333333
Saudi Arabia   -0.667896  1.149691            2   6  4.666667
Senegal        -1.214144  1.235077            1   3  1.750000
Serbia         -1.089807  0.875419            2   7  4.000000
Spain          -1.498758  0.554601            0   1  0.500000
Switzerland    -1.469082  0.754945            1   4  2.250000
Tunisia        -0.965692  1.031097            1   3  1.666667
United States  -1.136338  0.860862            0   4  1.250000
Uruguay        -0.931702  1.056570            1   3  2.000000
Wales          -0.971590  1.026174            1   2  1.666667

               Attempted Line Breaks                Possession (%)
                                 min       max  std           mean
Team
Argentina                  -1.027917  1.757406  1.0      49.285714
Australia                  -1.187623  0.961409  1.0      31.250000
Belgium                    -0.832050  1.109400  1.0      49.000000
Brazil                     -1.627519  1.085013  1.0      50.400000
Cameroon                   -1.124661  0.788942  1.0      38.333333
Canada                     -1.094819  0.865260  1.0      44.333333
Costa Rica                 -1.154606  0.590132  1.0      27.333333
Croatia                    -1.785063  1.187420  1.0      47.428571
Denmark                    -1.000000  1.000000  1.0      51.333333
Ecuador                    -0.979827  1.019020  1.0      42.666667
England                    -1.172641  1.354603  1.0      57.200000
France                     -1.327966  1.147789  1.0      44.857143
Germany                    -0.959538  1.036065  1.0      53.000000
Ghana                      -1.019578  0.979199  1.0      37.000000
Iran                       -1.152297  0.640642  1.0      31.666667
Japan                      -0.948495  1.377855  1.0      30.250000
Korea Republic             -1.449814  0.840338  1.0      42.250000
Mexico                     -1.154613  0.589590  1.0      46.666667
Morocco                    -1.718366  1.006855  1.0      34.285714
Netherlands                -1.222637  1.128588  1.0      44.000000
Poland                     -1.493418  0.626272  1.0      32.000000
Portugal                   -0.796941  1.655185  1.0      53.800000
Qatar                      -0.815368  1.115767  1.0      39.333333
Saudi Arabia               -1.022179  0.976238  1.0      36.666667
Senegal                    -1.077420  1.343085  1.0      38.500000
Serbia                     -0.916387  1.066614  1.0      42.666667
Spain                      -0.905726  1.193911  1.0      67.000000
Switzerland                -1.300880  1.024097  1.0      43.000000
Tunisia                    -1.119304  0.805353  1.0      38.666667
United States              -1.435367  0.767335  1.0      47.000000
Uruguay                    -0.665750  1.149932  1.0      41.000000
Wales                      -1.093756  0.867461  1.0      41.000000

## **Questions on IPL wala dataset**

ball by ball dataset - https://drive.google.com/file/d/1-kvv_9KCSAFWcrhS9WgTxSrURkRh6GNt/view?usp=share_link

###`Q-5:` Find batsman in below category-
* Highest score while chasing
* Best Strike rate while chasing and have faced 100+ balls


> Chasing mean team batting in second inning

In [1]:
# code here
import numpy as np
import pandas as pd
ipl_df = pd.read_csv('/content/deliveries.csv')
ipl_df

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179073,11415,2,Chennai Super Kings,Mumbai Indians,20,2,RA Jadeja,SR Watson,SL Malinga,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
179074,11415,2,Chennai Super Kings,Mumbai Indians,20,3,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179075,11415,2,Chennai Super Kings,Mumbai Indians,20,4,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,1,0,1,SR Watson,run out,KH Pandya
179076,11415,2,Chennai Super Kings,Mumbai Indians,20,5,SN Thakur,RA Jadeja,SL Malinga,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179077,11415,2,Chennai Super Kings,Mumbai Indians,20,6,SN Thakur,RA Jadeja,SL Malinga,0,...,0,0,0,0,0,0,0,SN Thakur,lbw,NaN

In [27]:
second_innings = ipl_df[ipl_df['inning'] == 2]
chasing_group = second_innings.groupby("batsman")
highest_score_while_chasing = chasing_group["batsman_runs"].sum().sort_values(ascending=False)
agg_stats = chasing_group.agg({
    'batsman_runs' : 'sum',
    'ball' : 'size'
})
agg_stats = agg_stats[agg_stats['ball'] > 100]
agg_stats['strike_rate'] = ((agg_stats['batsman_runs'] / agg_stats['ball']) * 100).round()
agg_stats.sort_values(by='batsman_runs', ascending=False)

             batsman_runs  ball  strike_rate
batsman
RV Uthappa           2622  1981        132.0
V Kohli              2553  1978        129.0
G Gambhir            2464  2116        116.0
SK Raina             2299  1705        135.0
DA Warner            2170  1535        141.0
...                   ...   ...          ...
PA Reddy              116   108        107.0
SK Warne              115   114        101.0
B Kumar               108   121         89.0
Niraj Patel           107   102        105.0
K Goel                 97   122         80.0

[156 rows x 3 columns]

###`Q-6` Most Successful bowler against any batsman. Find that pair of bowler and batsman.
> Most Successful in terms of dissmissal. A bowler who have dissmissed any batsman most no of times. If any two pairs have same no of dissmisal, consider runs conceded by bowler to that batsman. Those who have concede lesser runs is more successful.

In [8]:
# code here
ipl_df.groupby(["bowler", 'batsman'])["player_dismissed"].value_counts().sort_values(ascending=False).head(1)

bowler  batsman   player_dismissed
Z Khan  MS Dhoni  MS Dhoni            7
Name: count, dtype: int64

###`Q-7`: Most successful batting pair in IPL. Batting pair who have scored most runs playing together.

In [ ]:
# code here
ipl_df.groupby(["batsman", "non_striker"])["total_runs"].sum().sort_values(ascending=False).head(1)

batsman   non_striker
CH Gayle  V Kohli        1617
Name: total_runs, dtype: int64

In [ ]:
ipl_df['pair'] = ipl_df.apply(lambda x: tuple(sorted([x['batsman'], x['non_striker']])), axis=1)
ipl_df.groupby(['pair'])["total_runs"].sum().sort_values(ascending=False).head(1)

pair
(AB de Villiers, V Kohli)    2860
Name: total_runs, dtype: int64

###`Q-8:` Make a dataframe for all batting pairs played together.
```
Batsman1 Batsman2 Runs Avg StrikeRate
```

> Just to ease this question you can count wide-balls for strike rate.

In [43]:
# code here
ipl_df['pair'] = ipl_df.apply(lambda x: tuple(sorted([x['batsman'], x['non_striker']])), axis=1)
pair_group = ipl_df.groupby(['pair'])

total_runs = pair_group["total_runs"].sum().sort_values(ascending=False).reset_index()

balls_faced = pair_group['ball'].count()
total_runs['balls_faced'] = total_runs['pair'].map(balls_faced)

total_runs['strike_rate'] = (total_runs['total_runs'] / total_runs['balls_faced']) * 100

overs = (pair_group['over'].count()/6).round(2)
total_runs['overs'] = total_runs['pair'].map(overs)
total_runs['avg_run_rate'] = total_runs['total_runs']/total_runs['overs']

total_runs

,pair,total_runs,balls_faced,strike_rate,overs,avg_run_rate
0,"(AB de Villiers, V Kohli)",2860,1862,153.598281,310.33,9.215996
1,"(CH Gayle, V Kohli)",2802,1973,142.017233,328.83,8.521120
2,"(DA Warner, S Dhawan)",2357,1725,136.637681,287.50,8.198261
3,"(G Gambhir, RV Uthappa)",1906,1425,133.754386,237.50,8.025263
4,"(MS Dhoni, SK Raina)",1464,1055,138.767773,175.83,8.326224
...,...,...,...,...,...,...
3425,"(Ankit Sharma, Rashid Khan)",0,1,0.000000,0.17,0.000000
3426,"(Ankit Sharma, TP Sudhindra)",0,1,0.000000,0.17,0.000000
3427,"(MA Starc, S Aravind)",0,1,0.000000,0.17,0.000000
3428,"(A Chandila, OA Shah)",0,1,0.000000,0.17,0.000000
3429,"(A Choudhary, S Badree)",0,1,0.000000,0.17,0.000000